#!/usr/bin/env bash

set -x

# Scripting things
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Tiling

yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

yabai -m config window_border_width 6

yabai -m config mouse_modifier fn
yabai -m config mouse_actions1 move
yabai -m config mouse_actions2 resize

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on

yabai -m config window_topmost on

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.85

# Status bar

yabai -m config external_bar main:30:0
yabai -m config external_bar all:30:0
yabai -m config menubar_opacity 0.5


# Window rules

yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off
yabai -m rule --add app='^Arc$' title='' manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Spotify" manage=on
yabai -m rule --add app="TickTick" title="^$" manage=off
