#! /bin/sh

pgrep -x sxhkd -c ~/.config/bspwm/sxhkdrc > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color #FDF6E3

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

~/.config/bspwm/solarized-bar.sh | lemonbar -pf "Iosevka Nerd Font" &
alttab -w 1 -bg "#002B36" -fg "#FDF6E3" -frame "#657b83" -font "xft:Iosevka" &
conky -c ~/.config/bspwm/solarized-conky &
dunst -config ~/.config/bspwm/RelatedConfigs/dunstrc &
# $HOME/Documents/Scripts/Passwords.sh

